### ISSUE TITLE
No wifi connection after installing component

### ISSUE THREAD

**Issue by AllardKatan** [CoMPaTech/esphome_ct#10]
I've tried installing this on a NodeMCUV2 board, the install works and I can connect through a USB connection but there is no Wifi connectivity. I've confirmed that the board itself can connect, if I make a new blank device I get connectivity. If I then edit the YAML to include the CC1101 code and fan definitions it installs just fine but WiFi is lost. I also do not find the fallback AP. The log file has a part with non-text jibberish and reports unsuccesful boot attempts:
```
[13:43:26]rd$ܟ<�l�|�d�c|����;�#�c��'o�$gn���cp��${l{$8�g��l��cg�|���c��o'�lćd`�g'd`gs���oc$�lx�o�sĜ����cg�|�c��gn�d`�ogl`or���n#��`r��'c��`�쏜�d`��g�d����o��s��n|��l�;lc��|s�$�'��o�l ��{�d�d��[I][logger:034]: Log initialized
[13:43:26][C][safe_mode:079]: There have been 7 suspected unsuccessful boot attempts
[13:43:26][I][app:029]: Running through setup()...
[13:43:26][D][cc1101_fan:033]: restoring
[13:43:26][D][fan:120]: 'Mechanical Fan' - Sending state:
[13:43:26][D][fan:121]:   State: ON
[13:43:26][D][fan:123]:   Speed: 0
```
I've tried a few things: 

1. changing the board type in the code back to `d1 mini` as per the original. Didn't make a difference. 
2. switching the pin 6 connector of the CC1101 from D2 to the D1 pin of the ESP. I tried this because the code under 'fan:' lists a pin 'D1' which is not connected according to your wiring diagram. I don't know if that is supposed to be that way? In any case, this did not make a difference either.

Here is my YAML file (passwords and keys redacted)
```
esphome:
  name: fancontrol
  friendly_name: Itho_fan_controller
  libraries:
    - SPI
    - Ticker

esp8266:
  board: nodemcuv2


# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "******************************************"

ota:
  - platform: esphome
    password: "********************************"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Itho-Fan-Controller"
    password: "************"

captive_portal:


external_components:
  - source: 
      type: git
      url: https://github.com/CoMPaTech/esphome_ct
      ref: dev2
    # refresh: 3600s # only set this briefly otherwise it just refreshes daily, see https://esphome.io/components/external_components#external-components-refresh for setting refresh too low

fan:
  - platform: "cc1101"
    speed_count: 3
    name: "Mechanical Fan"
    data_pin: D1
    map_off_to_zero: True
    id: mech_fan

button:
  - platform: template
    name: "Send join command"
    on_press:
      then:
        - lambda: |-
            ((cc1101fan::CC1101Fan*)(&id(mech_fan)))->send_other_command(0);
  - platform: template
    name: "Run Timer for 10 Minutes"
    on_press:
      then:
        - lambda: |-
            ((cc1101fan::CC1101Fan*)(&id(mech_fan)))->send_other_command(1);
  - platform: template
    name: "Run Timer for 20 Minutes"
    on_press:
      then:
        - lambda: |-
            ((cc1101fan::CC1101Fan*)(&id(mech_fan)))->send_other_command(2);
  - platform: template
    name: "Run Timer for 30 Minutes"
    on_press:
      then:
        - lambda: |-
            ((cc1101fan::CC1101Fan*)(&id(mech_fan)))->send_other_command(3);

```
